let nome = "Felippe Almeida"
console.log("Nome antes: " + nome)

nome = "Jackeline Almeida"
console.log("Nome depois: " + nome)

nome = "Maria Almeida"
console.log("Nome no final: " + nome)

// CONST não pode ser alterada depois
const nomeCompleto = "Luiz Silva"
console.log("Nome antes: " + nomeCompleto)

// AQUI vai da erro
nomeCompleto ="Maria Eduarda Silva"
console.log("Nome completo depois: " + nomeCompleto)

nomeCompleto = "Sextouu"

console.log("Sextouu")



